---
- name: Deploy MySQL Server on AWS EC2
  hosts: dbservers
  become: true
  vars:
    mysql_root_password: 'StrongRootPassword123'
    mysql_bind_address: '0.0.0.0'

  tasks:
    - name: Ensure MySQL is installed
      ansible.builtin.apt:
        name: mysql-server
        state: present
        update_cache: yes

    - name: Ensure MySQL is started and enabled
      ansible.builtin.service:
        name: mysql
        state: started
        enabled: true

    - name: Set MySQL root password
      ansible.builtin.mysql_user:
        name: root
        host: localhost
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        check_implicit_admin: true
        state: present

    - name: Configure MySQL to listen on all interfaces
      ansible.builtin.lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: "bind-address = {{ mysql_bind_address }}"
        notify: Restart MySQL

    - name: Allow remote root login (optional, for testing)
      ansible.builtin.mysql_user:
        name: root
        host: '%'
        password: "{{ mysql_root_password }}"
        priv: '*.*:ALL,GRANT'
        login_user: root
        login_password: "{{ mysql_root_password }}"
        state: present

    - name: Open MySQL port (3306) in UFW firewall
      ansible.builtin.ufw:
        rule: allow
        port: '3306'
        proto: tcp

  handlers:
    - name: Restart MySQL
      ansible.builtin.service:
        name: mysql
        state: restarted
